[package]
name = "app"
version = "0.1.0"
description = "Pake 打包工具"
authors = ["Tw93"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.61.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }


[dependencies]
serde_json = "1.0.86"
serde = { version = "1.0.145", features = ["derive"] }
tauri = { version = "1.2.0", features = ["api-all"] }
image = "0.24.5"
tauri-utils = "1.2.0"
webbrowser = "0.8.2"

[dependencies.wry]
git = "https://github.com/tauri-apps/wry.git"
rev = "7c6d64acea4414f7c960b38b80ea9ec3628db2a8"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
# Enable DevTools for debugging.
devtools = []
